# Generated by Django 5.1.3 on 2024-11-26 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم جهة التدريب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الجهة')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان')),
                ('contact_person', models.CharField(max_length=100, verbose_name='الشخص المسؤول')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للتواصل')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف للتواصل')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('available_positions', models.TextField(blank=True, null=True, verbose_name='الوظائف المتاحة')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('both', 'الكل')], default='both', max_length=10, verbose_name='الجنس')),
                ('min_hours', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى من الساعات')),
                ('available_slots', models.PositiveIntegerField(default=1, verbose_name='عدد الطلاب المتاح')),
                ('semester', models.CharField(choices=[('first', 'الفصل الأول'), ('second', 'الفصل الثاني'), ('summer', 'الفصل الصيفي')], max_length=10, verbose_name='الفصل الدراسي')),
                ('is_available', models.BooleanField(default=False, verbose_name='متاح للطلاب')),
                ('departments', models.ManyToManyField(to='training.department', verbose_name='الأقسام')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('tasks_assigned', models.TextField(verbose_name='المهام الموكلة')),
                ('skills_learned', models.TextField(verbose_name='المهارات المكتسبة')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_training_details', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('supervisor', models.ForeignKey(limit_choices_to={'user_type': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_training_details', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
                ('training_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.trainingentity', verbose_name='جهة التدريب')),
            ],
        ),
        migrations.CreateModel(
            name='LetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('training_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingentity', verbose_name='جهة التدريب')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('motivation_letter', models.TextField(verbose_name='رسالة الدافع')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='training_requests/', verbose_name='المستندات الإضافية')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('training_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingentity', verbose_name='جهة التدريب')),
            ],
        ),
    ]
