# Generated by Django 5.1.3 on 2025-01-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterrequest',
            name='training_entity',
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='entity_address',
            field=models.CharField(default='N/A', max_length=300, verbose_name='عنوان جهة التدريب'),
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='entity_contact_email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='البريد الإلكتروني للتواصل'),
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='entity_contact_person',
            field=models.CharField(default='N/A', max_length=100, verbose_name='الشخص المسؤول'),
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='entity_contact_phone',
            field=models.CharField(default='N/A', max_length=20, verbose_name='رقم الهاتف للتواصل'),
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='entity_name',
            field=models.CharField(default='N/A', max_length=200, verbose_name='اسم جهة التدريب'),
        ),
    ]
