# Generated by Django 5.1.2 on 2024-12-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('max_score', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للدرجة')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('total_score', models.PositiveIntegerField(verbose_name='الدرجة الإجمالية')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='التعليقات')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('training_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingentity', verbose_name='وحدة التدريب')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='الدرجة')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriteria', verbose_name='المعيار')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.evaluation', verbose_name='التقييم')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('description', models.TextField(verbose_name='وصف النموذج')),
                ('criteria', models.ManyToManyField(to='evaluations.evaluationcriteria', verbose_name='المعايير')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.evaluationtemplate', verbose_name='نموذج التقييم'),
        ),
    ]
