# Generated by Django 5.1.3 on 2024-12-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('evaluation_type', models.CharField(choices=[('student', 'تقييم الطالب'), ('entity', 'تقييم جهة التدريب')], default='student', max_length=10, verbose_name='نوع التقييم')),
                ('c1_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 1')),
                ('c2_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 2')),
                ('c3_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 3')),
                ('c4_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 4')),
                ('c5_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 5')),
                ('c6_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 6')),
                ('c7_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 7')),
                ('c8_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 8')),
                ('c9_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 9')),
                ('c10_score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], default=10, verbose_name='المعيار 10')),
                ('total_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='الدرجة الإجمالية')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='التعليقات')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('training_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingentity', verbose_name='وحدة التدريب')),
            ],
        ),
    ]
