# Generated by Django 5.1.3 on 2024-12-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationtemplate",
            name="criteria",
        ),
        migrations.RemoveField(
            model_name="evaluationitem",
            name="criteria",
        ),
        migrations.RemoveField(
            model_name="evaluationitem",
            name="evaluation",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="template",
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c10_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 10",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c1_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 1",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c2_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 2",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c3_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 3",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c4_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 4",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c5_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 5",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c6_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 6",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c7_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 7",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c8_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 8",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="c9_score",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "ممتاز"),
                    (8, "جيد جدا"),
                    (6, "جيد"),
                    (4, "مقبول"),
                    (2, "ضعيف"),
                ],
                default=10,
                verbose_name="المعيار 9",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evaluation_type",
            field=models.CharField(
                choices=[("student", "تقييم الطالب"), ("entity", "تقييم جهة التدريب")],
                default="student",
                max_length=10,
                verbose_name="نوع التقييم",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="total_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الدرجة الإجمالية"
            ),
        ),
        migrations.DeleteModel(
            name="EvaluationCriteria",
        ),
        migrations.DeleteModel(
            name="EvaluationItem",
        ),
        migrations.DeleteModel(
            name="EvaluationTemplate",
        ),
    ]
