# Generated by Django 5.1.2 on 2024-12-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'تقرير أسبوعي'), ('final', 'تقرير نهائي')], max_length=20, verbose_name='نوع التقرير')),
                ('file', models.FileField(upload_to='reports/', verbose_name='الملف')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة التقرير')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
        ),
    ]
